### ISSUE TITLE
Ensure "package downloads" and other reports contain all package identities

### ISSUE THREAD

**Issue by loic-sharma** [joelverhagen/ExplorePackages#24]
Currently the "package downloads" report does not have all package identities. This report should be joined with `kind=leftouter`.

Ideally, all tables should have the same set of distinct `Identity` values. We can consider using the "package versions" report to fill missing records with sensible default data. For example, if a package exists in "package versions" but not in "package downloads", we could insert a record for tha missing package with downloads of 0.

**Comment by joelverhagen** [comment]
Done.
